const blackout = [
	{
		id: 'base1-62',
		name: 'Sandshrew',
		imageUrl: 'https://images.pokemontcg.io/base1/62.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '62',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Sand-attack',
				cost: ['Fighting'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					"If the Defending Pokémon tries to attack during your opponent's next turn, your opponent flips a coin. If tails, that attack does nothing.",
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Lightning',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/62_hires.png',
		nationalPokedexNumber: 27,
		evolvesTo: ['Sandslash'],
	},
	{
		id: 'base1-62',
		name: 'Sandshrew',
		imageUrl: 'https://images.pokemontcg.io/base1/62.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '62',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Sand-attack',
				cost: ['Fighting'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					"If the Defending Pokémon tries to attack during your opponent's next turn, your opponent flips a coin. If tails, that attack does nothing.",
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Lightning',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/62_hires.png',
		nationalPokedexNumber: 27,
		evolvesTo: ['Sandslash'],
	},
	{
		id: 'base1-62',
		name: 'Sandshrew',
		imageUrl: 'https://images.pokemontcg.io/base1/62.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '62',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Sand-attack',
				cost: ['Fighting'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					"If the Defending Pokémon tries to attack during your opponent's next turn, your opponent flips a coin. If tails, that attack does nothing.",
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Lightning',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/62_hires.png',
		nationalPokedexNumber: 27,
		evolvesTo: ['Sandslash'],
	},
	{
		id: 'base1-52',
		name: 'Machop',
		imageUrl: 'https://images.pokemontcg.io/base1/52.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '20',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '52',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Low Kick',
				cost: ['Fighting'],
				convertedEnergyCost: 1,
				damage: '20',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/52_hires.png',
		nationalPokedexNumber: 66,
		evolvesTo: ['Machoke'],
	},
	{
		id: 'base1-52',
		name: 'Machop',
		imageUrl: 'https://images.pokemontcg.io/base1/52.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '20',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '52',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Low Kick',
				cost: ['Fighting'],
				convertedEnergyCost: 1,
				damage: '20',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/52_hires.png',
		nationalPokedexNumber: 66,
		evolvesTo: ['Machoke'],
	},
	{
		id: 'base1-52',
		name: 'Machop',
		imageUrl: 'https://images.pokemontcg.io/base1/52.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '20',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '52',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Low Kick',
				cost: ['Fighting'],
				convertedEnergyCost: 1,
				damage: '20',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/52_hires.png',
		nationalPokedexNumber: 66,
		evolvesTo: ['Machoke'],
	},
	{
		id: 'base1-52',
		name: 'Machop',
		imageUrl: 'https://images.pokemontcg.io/base1/52.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '20',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '52',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Low Kick',
				cost: ['Fighting'],
				convertedEnergyCost: 1,
				damage: '20',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/52_hires.png',
		nationalPokedexNumber: 66,
		evolvesTo: ['Machoke'],
	},
	{
		id: 'base1-34',
		name: 'Machoke',
		imageUrl: 'https://images.pokemontcg.io/base1/34.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '40',
		evolvesFrom: 'Machop',
		hp: '80',
		retreatCost: ['Colorless', 'Colorless', 'Colorless'],
		convertedRetreatCost: 3,
		number: '34',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Karate Chop',
				cost: ['Fighting', 'Fighting', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '50-',
				text:
					'Does 50 damage minus 10 for each damage counter on Machoke.',
			},
			{
				name: 'Submission',
				cost: ['Fighting', 'Fighting', 'Colorless', 'Colorless'],
				convertedEnergyCost: 4,
				damage: '60',
				text: 'Machoke does 20 damage to itself.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/34_hires.png',
		nationalPokedexNumber: 67,
		evolvesTo: ['Machamp'],
	},
	{
		id: 'base1-34',
		name: 'Machoke',
		imageUrl: 'https://images.pokemontcg.io/base1/34.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '40',
		evolvesFrom: 'Machop',
		hp: '80',
		retreatCost: ['Colorless', 'Colorless', 'Colorless'],
		convertedRetreatCost: 3,
		number: '34',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Karate Chop',
				cost: ['Fighting', 'Fighting', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '50-',
				text:
					'Does 50 damage minus 10 for each damage counter on Machoke.',
			},
			{
				name: 'Submission',
				cost: ['Fighting', 'Fighting', 'Colorless', 'Colorless'],
				convertedEnergyCost: 4,
				damage: '60',
				text: 'Machoke does 20 damage to itself.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/34_hires.png',
		nationalPokedexNumber: 67,
		evolvesTo: ['Machamp'],
	},
	{
		id: 'base1-56',
		name: 'Onix',
		imageUrl: 'https://images.pokemontcg.io/base1/56.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '90',
		retreatCost: ['Colorless', 'Colorless', 'Colorless'],
		convertedRetreatCost: 3,
		number: '56',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Rock Throw',
				cost: ['Fighting'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Harden',
				cost: ['Fighting', 'Fighting'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"During opponent's next turn, whenever 30 or less damage is done to Onix (after applying Weakness and Resistance), prevent that damage. (Any other effects of attacks still happen.)",
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/56_hires.png',
		nationalPokedexNumber: 95,
		evolvesTo: ['Steelix'],
	},
	{
		id: 'base1-56',
		name: 'Onix',
		imageUrl: 'https://images.pokemontcg.io/base1/56.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '90',
		retreatCost: ['Colorless', 'Colorless', 'Colorless'],
		convertedRetreatCost: 3,
		number: '56',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Rock Throw',
				cost: ['Fighting'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Harden',
				cost: ['Fighting', 'Fighting'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"During opponent's next turn, whenever 30 or less damage is done to Onix (after applying Weakness and Resistance), prevent that damage. (Any other effects of attacks still happen.)",
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/56_hires.png',
		nationalPokedexNumber: 95,
		evolvesTo: ['Steelix'],
	},
	{
		id: 'base1-56',
		name: 'Onix',
		imageUrl: 'https://images.pokemontcg.io/base1/56.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '90',
		retreatCost: ['Colorless', 'Colorless', 'Colorless'],
		convertedRetreatCost: 3,
		number: '56',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Rock Throw',
				cost: ['Fighting'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Harden',
				cost: ['Fighting', 'Fighting'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"During opponent's next turn, whenever 30 or less damage is done to Onix (after applying Weakness and Resistance), prevent that damage. (Any other effects of attacks still happen.)",
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/56_hires.png',
		nationalPokedexNumber: 95,
		evolvesTo: ['Steelix'],
	},
	{
		id: 'base1-7',
		name: 'Hitmonchan',
		imageUrl: 'https://images.pokemontcg.io/base1/7.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '33',
		hp: '70',
		retreatCost: ['Colorless', 'Colorless'],
		convertedRetreatCost: 2,
		number: '7',
		artist: 'Ken Sugimori',
		rarity: 'Rare',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Jab',
				cost: ['Fighting'],
				convertedEnergyCost: 1,
				damage: '20',
				text: '',
			},
			{
				name: 'Special Punch',
				cost: ['Fighting', 'Fighting', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '40',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/7_hires.png',
		nationalPokedexNumber: 107,
	},
	{
		id: 'base1-63',
		name: 'Squirtle',
		imageUrl: 'https://images.pokemontcg.io/base1/63.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '8',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '63',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Bubble',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
			{
				name: 'Withdraw',
				cost: ['Water', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Flip a coin. If heads, prevent all damage done to Squirtle during your opponent's next turn. (Any other effects of attacks still happen.)",
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/63_hires.png',
		nationalPokedexNumber: 7,
		evolvesTo: ['Wartortle'],
	},
	{
		id: 'base1-63',
		name: 'Squirtle',
		imageUrl: 'https://images.pokemontcg.io/base1/63.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '8',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '63',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Bubble',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
			{
				name: 'Withdraw',
				cost: ['Water', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Flip a coin. If heads, prevent all damage done to Squirtle during your opponent's next turn. (Any other effects of attacks still happen.)",
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/63_hires.png',
		nationalPokedexNumber: 7,
		evolvesTo: ['Wartortle'],
	},
	{
		id: 'base1-63',
		name: 'Squirtle',
		imageUrl: 'https://images.pokemontcg.io/base1/63.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '8',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '63',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Bubble',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
			{
				name: 'Withdraw',
				cost: ['Water', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Flip a coin. If heads, prevent all damage done to Squirtle during your opponent's next turn. (Any other effects of attacks still happen.)",
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/63_hires.png',
		nationalPokedexNumber: 7,
		evolvesTo: ['Wartortle'],
	},
	{
		id: 'base1-63',
		name: 'Squirtle',
		imageUrl: 'https://images.pokemontcg.io/base1/63.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '8',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '63',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Bubble',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
			{
				name: 'Withdraw',
				cost: ['Water', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Flip a coin. If heads, prevent all damage done to Squirtle during your opponent's next turn. (Any other effects of attacks still happen.)",
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/63_hires.png',
		nationalPokedexNumber: 7,
		evolvesTo: ['Wartortle'],
	},
	{
		id: 'base1-42',
		name: 'Wartortle',
		imageUrl: 'https://images.pokemontcg.io/base1/42.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '22',
		evolvesFrom: 'Squirtle',
		hp: '70',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '42',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Withdraw',
				cost: ['Water', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Flip a coin. If heads, prevent all damage done to Wartortle during your opponent's next turn. (Any other effects of attacks still happen.)",
			},
			{
				name: 'Bite',
				cost: ['Water', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '40',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/42_hires.png',
		nationalPokedexNumber: 8,
		evolvesTo: ['Blastoise'],
	},
	{
		id: 'base1-42',
		name: 'Wartortle',
		imageUrl: 'https://images.pokemontcg.io/base1/42.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '22',
		evolvesFrom: 'Squirtle',
		hp: '70',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '42',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Withdraw',
				cost: ['Water', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Flip a coin. If heads, prevent all damage done to Wartortle during your opponent's next turn. (Any other effects of attacks still happen.)",
			},
			{
				name: 'Bite',
				cost: ['Water', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '40',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/42_hires.png',
		nationalPokedexNumber: 8,
		evolvesTo: ['Blastoise'],
	},
	{
		id: 'base1-65',
		name: 'Staryu',
		imageUrl: 'https://images.pokemontcg.io/base1/65.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '15',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '65',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Slap',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '20',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/65_hires.png',
		nationalPokedexNumber: 120,
		evolvesTo: ['Starmie'],
	},
	{
		id: 'base1-65',
		name: 'Staryu',
		imageUrl: 'https://images.pokemontcg.io/base1/65.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '15',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '65',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Slap',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '20',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/65_hires.png',
		nationalPokedexNumber: 120,
		evolvesTo: ['Starmie'],
	},
	{
		id: 'base1-65',
		name: 'Staryu',
		imageUrl: 'https://images.pokemontcg.io/base1/65.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '15',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '65',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Slap',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '20',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/65_hires.png',
		nationalPokedexNumber: 120,
		evolvesTo: ['Starmie'],
	},
	{
		id: 'base1-27',
		name: "Farfetch'd",
		imageUrl: 'https://images.pokemontcg.io/base1/27.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '20',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '27',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Colorless'],
		attacks: [
			{
				name: 'Leek Slap',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '30',
				text:
					"Flip a coin. If tails, this attack does nothing. Either way, you can't use this attack again as long as Farfetch'd stays in play (even putting Farfetch'd on the Bench won't let you use it again.)",
			},
			{
				name: 'Pot Smash',
				cost: ['Colorless', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Fighting',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/27_hires.png',
		nationalPokedexNumber: 83,
	},
	{
		id: 'base1-27',
		name: "Farfetch'd",
		imageUrl: 'https://images.pokemontcg.io/base1/27.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '20',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '27',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Colorless'],
		attacks: [
			{
				name: 'Leek Slap',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '30',
				text:
					"Flip a coin. If tails, this attack does nothing. Either way, you can't use this attack again as long as Farfetch'd stays in play (even putting Farfetch'd on the Bench won't let you use it again.)",
			},
			{
				name: 'Pot Smash',
				cost: ['Colorless', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Fighting',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/27_hires.png',
		nationalPokedexNumber: 83,
	},
	{
		id: 'base1-92',
		name: 'Energy Removal',
		imageUrl: 'https://images.pokemontcg.io/base1/92.png',
		subtype: '',
		supertype: 'Trainer',
		number: '92',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Choose 1 Energy card attached to 1 of your opponent's Pokémon and discard it.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/92_hires.png',
	},
	{
		id: 'base1-92',
		name: 'Energy Removal',
		imageUrl: 'https://images.pokemontcg.io/base1/92.png',
		subtype: '',
		supertype: 'Trainer',
		number: '92',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Choose 1 Energy card attached to 1 of your opponent's Pokémon and discard it.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/92_hires.png',
	},
	{
		id: 'base1-92',
		name: 'Energy Removal',
		imageUrl: 'https://images.pokemontcg.io/base1/92.png',
		subtype: '',
		supertype: 'Trainer',
		number: '92',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Choose 1 Energy card attached to 1 of your opponent's Pokémon and discard it.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/92_hires.png',
	},
	{
		id: 'base1-92',
		name: 'Energy Removal',
		imageUrl: 'https://images.pokemontcg.io/base1/92.png',
		subtype: '',
		supertype: 'Trainer',
		number: '92',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Choose 1 Energy card attached to 1 of your opponent's Pokémon and discard it.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/92_hires.png',
	},
	{
		id: 'base1-93',
		name: 'Gust of Wind',
		imageUrl: 'https://images.pokemontcg.io/base1/93.png',
		subtype: '',
		supertype: 'Trainer',
		number: '93',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Choose 1 of your opponent's Benched Pokémon and switch it with his or her Active Pokémon.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/93_hires.png',
	},
	{
		id: 'base1-84',
		name: 'PlusPower',
		imageUrl: 'https://images.pokemontcg.io/base1/84.png',
		subtype: '',
		supertype: 'Trainer',
		number: '84',
		artist: 'Keiji Kinebuchi',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Attach PlusPower to your Active Pokémonn. At the end of your turn, discard PlusPower. If this Pokémon's attack does damage to the defending Pokémon (after applying Weakness and Resistance), the attack does 10 more damage to the Defending Pokémon.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/84_hires.png',
	},
	{
		id: 'base1-88',
		name: 'Professor Oak',
		imageUrl: 'https://images.pokemontcg.io/base1/88.png',
		subtype: '',
		supertype: 'Trainer',
		number: '88',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Discard your hand, then draw 7 cards.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/88_hires.png',
	},
	{
		id: 'base1-79',
		name: 'Super Energy Removal',
		imageUrl: 'https://images.pokemontcg.io/base1/79.png',
		subtype: '',
		supertype: 'Trainer',
		number: '79',
		artist: 'Keiji Kinebuchi',
		rarity: 'Rare',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Discard 1 Energy card attached to 1 of your own Pokémon in order to choose 1 of your opponent's Pokémon and up to 2 Energy cards attached to it. Discard those energy cards.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/79_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
];

module.exports = blackout;
