const brushfire = [
	{
		id: 'base1-46',
		name: 'Charmander',
		imageUrl: 'https://images.pokemontcg.io/base1/46.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '10',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '46',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fire'],
		attacks: [
			{
				name: 'Scratch',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Ember',
				cost: ['Fire', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '30',
				text:
					'Discard 1 Energy card attached to Charmander in order to use this attack.',
			},
		],
		weaknesses: [
			{
				type: 'Water',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/46_hires.png',
		nationalPokedexNumber: 4,
		evolvesTo: ['Charmeleon'],
	},
	{
		id: 'base1-46',
		name: 'Charmander',
		imageUrl: 'https://images.pokemontcg.io/base1/46.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '10',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '46',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fire'],
		attacks: [
			{
				name: 'Scratch',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Ember',
				cost: ['Fire', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '30',
				text:
					'Discard 1 Energy card attached to Charmander in order to use this attack.',
			},
		],
		weaknesses: [
			{
				type: 'Water',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/46_hires.png',
		nationalPokedexNumber: 4,
		evolvesTo: ['Charmeleon'],
	},
	{
		id: 'base1-46',
		name: 'Charmander',
		imageUrl: 'https://images.pokemontcg.io/base1/46.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '10',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '46',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fire'],
		attacks: [
			{
				name: 'Scratch',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Ember',
				cost: ['Fire', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '30',
				text:
					'Discard 1 Energy card attached to Charmander in order to use this attack.',
			},
		],
		weaknesses: [
			{
				type: 'Water',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/46_hires.png',
		nationalPokedexNumber: 4,
		evolvesTo: ['Charmeleon'],
	},
	{
		id: 'base1-46',
		name: 'Charmander',
		imageUrl: 'https://images.pokemontcg.io/base1/46.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '10',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '46',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fire'],
		attacks: [
			{
				name: 'Scratch',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Ember',
				cost: ['Fire', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '30',
				text:
					'Discard 1 Energy card attached to Charmander in order to use this attack.',
			},
		],
		weaknesses: [
			{
				type: 'Water',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/46_hires.png',
		nationalPokedexNumber: 4,
		evolvesTo: ['Charmeleon'],
	},
	{
		id: 'base1-24',
		name: 'Charmeleon',
		imageUrl: 'https://images.pokemontcg.io/base1/24.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '32',
		evolvesFrom: 'Charmander',
		hp: '80',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '24',
		artist: 'Mitsuhiro Arita',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fire'],
		attacks: [
			{
				name: 'Slash',
				cost: ['Colorless', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30',
				text: '',
			},
			{
				name: 'Flamethrower',
				cost: ['Fire', 'Fire', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '50',
				text:
					'Discard 1 Energy card attached to Charmeleon in order to use this attack.',
			},
		],
		weaknesses: [
			{
				type: 'Water',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/24_hires.png',
		nationalPokedexNumber: 5,
		evolvesTo: ['Charizard'],
	},
	{
		id: 'base1-24',
		name: 'Charmeleon',
		imageUrl: 'https://images.pokemontcg.io/base1/24.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '32',
		evolvesFrom: 'Charmander',
		hp: '80',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '24',
		artist: 'Mitsuhiro Arita',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fire'],
		attacks: [
			{
				name: 'Slash',
				cost: ['Colorless', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30',
				text: '',
			},
			{
				name: 'Flamethrower',
				cost: ['Fire', 'Fire', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '50',
				text:
					'Discard 1 Energy card attached to Charmeleon in order to use this attack.',
			},
		],
		weaknesses: [
			{
				type: 'Water',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/24_hires.png',
		nationalPokedexNumber: 5,
		evolvesTo: ['Charizard'],
	},
	{
		id: 'base1-68',
		name: 'Vulpix',
		imageUrl: 'https://images.pokemontcg.io/base1/68.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '11',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '68',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fire'],
		attacks: [
			{
				name: 'Confuse Ray',
				cost: ['Fire', 'Fire'],
				convertedEnergyCost: 2,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Confused.',
			},
		],
		weaknesses: [
			{
				type: 'Water',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/68_hires.png',
		nationalPokedexNumber: 37,
		evolvesTo: ['Ninetales'],
	},
	{
		id: 'base1-68',
		name: 'Vulpix',
		imageUrl: 'https://images.pokemontcg.io/base1/68.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '11',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '68',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fire'],
		attacks: [
			{
				name: 'Confuse Ray',
				cost: ['Fire', 'Fire'],
				convertedEnergyCost: 2,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Confused.',
			},
		],
		weaknesses: [
			{
				type: 'Water',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/68_hires.png',
		nationalPokedexNumber: 37,
		evolvesTo: ['Ninetales'],
	},
	{
		id: 'base1-12',
		name: 'Ninetales',
		imageUrl: 'https://images.pokemontcg.io/base1/12.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '32',
		evolvesFrom: 'Vulpix',
		hp: '80',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '12',
		artist: 'Ken Sugimori',
		rarity: 'Rare',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fire'],
		attacks: [
			{
				name: 'Lure',
				cost: ['Colorless', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					'If your opponent has any Benched Pokémon, choose 1 of them and switch it with the Defending Pokémon.',
			},
			{
				name: 'Fire Blast',
				cost: ['Fire', 'Fire', 'Fire', 'Fire'],
				convertedEnergyCost: 4,
				damage: '80',
				text:
					'Discard 1 Energy card attached to Ninetales in order to use this attack.',
			},
		],
		weaknesses: [
			{
				type: 'Water',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/12_hires.png',
		nationalPokedexNumber: 38,
	},
	{
		id: 'base1-28',
		name: 'Growlithe',
		imageUrl: 'https://images.pokemontcg.io/base1/28.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '18',
		hp: '60',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '28',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fire'],
		attacks: [
			{
				name: 'Flare',
				cost: ['Fire', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '20',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Water',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/28_hires.png',
		nationalPokedexNumber: 58,
		evolvesTo: ['Arcanine'],
	},
	{
		id: 'base1-28',
		name: 'Growlithe',
		imageUrl: 'https://images.pokemontcg.io/base1/28.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '18',
		hp: '60',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '28',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fire'],
		attacks: [
			{
				name: 'Flare',
				cost: ['Fire', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '20',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Water',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/28_hires.png',
		nationalPokedexNumber: 58,
		evolvesTo: ['Arcanine'],
	},
	{
		id: 'base1-23',
		name: 'Arcanine',
		imageUrl: 'https://images.pokemontcg.io/base1/23.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '45',
		evolvesFrom: 'Growlithe',
		hp: '100',
		retreatCost: ['Colorless', 'Colorless', 'Colorless'],
		convertedRetreatCost: 3,
		number: '23',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fire'],
		attacks: [
			{
				name: 'Flamethrower',
				cost: ['Fire', 'Fire', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '50',
				text:
					'Discard 1 Energy card attached to Arcanine in order to use this attack.',
			},
			{
				name: 'Take Down',
				cost: ['Fire', 'Fire', 'Colorless', 'Colorless'],
				convertedEnergyCost: 4,
				damage: '80',
				text: 'Arcanine does 30 damage to itself.',
			},
		],
		weaknesses: [
			{
				type: 'Water',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/23_hires.png',
		nationalPokedexNumber: 59,
	},
	{
		id: 'base1-69',
		name: 'Weedle',
		imageUrl: 'https://images.pokemontcg.io/base1/69.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '69',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Poison Sting',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, Defending Pokémon is now Poisoned.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/69_hires.png',
		nationalPokedexNumber: 13,
		evolvesTo: ['Kakuna'],
	},
	{
		id: 'base1-69',
		name: 'Weedle',
		imageUrl: 'https://images.pokemontcg.io/base1/69.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '69',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Poison Sting',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, Defending Pokémon is now Poisoned.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/69_hires.png',
		nationalPokedexNumber: 13,
		evolvesTo: ['Kakuna'],
	},
	{
		id: 'base1-69',
		name: 'Weedle',
		imageUrl: 'https://images.pokemontcg.io/base1/69.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '69',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Poison Sting',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, Defending Pokémon is now Poisoned.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/69_hires.png',
		nationalPokedexNumber: 13,
		evolvesTo: ['Kakuna'],
	},
	{
		id: 'base1-69',
		name: 'Weedle',
		imageUrl: 'https://images.pokemontcg.io/base1/69.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '69',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Poison Sting',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, Defending Pokémon is now Poisoned.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/69_hires.png',
		nationalPokedexNumber: 13,
		evolvesTo: ['Kakuna'],
	},
	{
		id: 'base1-55',
		name: 'Nidoran♂',
		imageUrl: 'https://images.pokemontcg.io/base1/55.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '20',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '55',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Horn Hazard',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '30',
				text: 'Flip a coin. If tails, this attack does nothing.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/55_hires.png',
		nationalPokedexNumber: 32,
		evolvesTo: ['Nidorino'],
	},
	{
		id: 'base1-55',
		name: 'Nidoran♂',
		imageUrl: 'https://images.pokemontcg.io/base1/55.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '20',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '55',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Horn Hazard',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '30',
				text: 'Flip a coin. If tails, this attack does nothing.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/55_hires.png',
		nationalPokedexNumber: 32,
		evolvesTo: ['Nidorino'],
	},
	{
		id: 'base1-55',
		name: 'Nidoran♂',
		imageUrl: 'https://images.pokemontcg.io/base1/55.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '20',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '55',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Horn Hazard',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '30',
				text: 'Flip a coin. If tails, this attack does nothing.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/55_hires.png',
		nationalPokedexNumber: 32,
		evolvesTo: ['Nidorino'],
	},
	{
		id: 'base1-55',
		name: 'Nidoran♂',
		imageUrl: 'https://images.pokemontcg.io/base1/55.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '20',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '55',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Horn Hazard',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '30',
				text: 'Flip a coin. If tails, this attack does nothing.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/55_hires.png',
		nationalPokedexNumber: 32,
		evolvesTo: ['Nidorino'],
	},
	{
		id: 'base1-66',
		name: 'Tangela',
		imageUrl: 'https://images.pokemontcg.io/base1/66.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '8',
		hp: '50',
		retreatCost: ['Colorless', 'Colorless'],
		convertedRetreatCost: 2,
		number: '66',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Bind',
				cost: ['Grass', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '20',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
			{
				name: 'Poisonpowder',
				cost: ['Grass', 'Grass', 'Grass'],
				convertedEnergyCost: 3,
				damage: '30',
				text: 'The Defending Pokémon is now Poisoned.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/66_hires.png',
		nationalPokedexNumber: 114,
		evolvesTo: ['Tangrowth'],
	},
	{
		id: 'base1-66',
		name: 'Tangela',
		imageUrl: 'https://images.pokemontcg.io/base1/66.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '8',
		hp: '50',
		retreatCost: ['Colorless', 'Colorless'],
		convertedRetreatCost: 2,
		number: '66',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Bind',
				cost: ['Grass', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '20',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
			{
				name: 'Poisonpowder',
				cost: ['Grass', 'Grass', 'Grass'],
				convertedEnergyCost: 3,
				damage: '30',
				text: 'The Defending Pokémon is now Poisoned.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/66_hires.png',
		nationalPokedexNumber: 114,
		evolvesTo: ['Tangrowth'],
	},
	{
		id: 'base1-92',
		name: 'Energy Removal',
		imageUrl: 'https://images.pokemontcg.io/base1/92.png',
		subtype: '',
		supertype: 'Trainer',
		number: '92',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Choose 1 Energy card attached to 1 of your opponent's Pokémon and discard it.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/92_hires.png',
	},
	{
		id: 'base1-81',
		name: 'Energy Retrieval',
		imageUrl: 'https://images.pokemontcg.io/base1/81.png',
		subtype: '',
		supertype: 'Trainer',
		number: '81',
		artist: 'Keiji Kinebuchi',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			'Trade 1 of other cards in your hand for up to 2 basic Energy cards from your discard pile.',
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/81_hires.png',
	},
	{
		id: 'base1-81',
		name: 'Energy Retrieval',
		imageUrl: 'https://images.pokemontcg.io/base1/81.png',
		subtype: '',
		supertype: 'Trainer',
		number: '81',
		artist: 'Keiji Kinebuchi',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			'Trade 1 of other cards in your hand for up to 2 basic Energy cards from your discard pile.',
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/81_hires.png',
	},
	{
		id: 'base1-93',
		name: 'Gust of Wind',
		imageUrl: 'https://images.pokemontcg.io/base1/93.png',
		subtype: '',
		supertype: 'Trainer',
		number: '93',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Choose 1 of your opponent's Benched Pokémon and switch it with his or her Active Pokémon.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/93_hires.png',
	},
	{
		id: 'base1-75',
		name: 'Lass',
		imageUrl: 'https://images.pokemontcg.io/base1/75.png',
		subtype: '',
		supertype: 'Trainer',
		number: '75',
		artist: 'Ken Sugimori',
		rarity: 'Rare',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			'You and your opponent show each other your hands, then shuffle all the trainer cards from your hands into your decks.',
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/75_hires.png',
	},
	{
		id: 'base1-84',
		name: 'PlusPower',
		imageUrl: 'https://images.pokemontcg.io/base1/84.png',
		subtype: '',
		supertype: 'Trainer',
		number: '84',
		artist: 'Keiji Kinebuchi',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Attach PlusPower to your Active Pokémonn. At the end of your turn, discard PlusPower. If this Pokémon's attack does damage to the defending Pokémon (after applying Weakness and Resistance), the attack does 10 more damage to the Defending Pokémon.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/84_hires.png',
	},
	{
		id: 'base1-94',
		name: 'Potion',
		imageUrl: 'https://images.pokemontcg.io/base1/94.png',
		subtype: '',
		supertype: 'Trainer',
		number: '94',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Remove up to 2 damage counters from 1 of your Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/94_hires.png',
	},
	{
		id: 'base1-94',
		name: 'Potion',
		imageUrl: 'https://images.pokemontcg.io/base1/94.png',
		subtype: '',
		supertype: 'Trainer',
		number: '94',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Remove up to 2 damage counters from 1 of your Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/94_hires.png',
	},
	{
		id: 'base1-94',
		name: 'Potion',
		imageUrl: 'https://images.pokemontcg.io/base1/94.png',
		subtype: '',
		supertype: 'Trainer',
		number: '94',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Remove up to 2 damage counters from 1 of your Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/94_hires.png',
	},
	{
		id: 'base1-95',
		name: 'Switch',
		imageUrl: 'https://images.pokemontcg.io/base1/95.png',
		subtype: '',
		supertype: 'Trainer',
		number: '95',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Switch 1 of your Benched Pokémon with your Active Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/95_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-98',
		name: 'Fire Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/98.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '98',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/98_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
];

module.exports = brushfire;
