const overgrowth = [
	{
		id: 'base1-44',
		name: 'Bulbasaur',
		imageUrl: 'https://images.pokemontcg.io/base1/44.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '13',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '44',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Leech Seed',
				cost: ['Grass', 'Grass'],
				convertedEnergyCost: 2,
				damage: '20',
				text:
					'Unless all damage from this attack is prevented, you may remove 1 damage counter from Bulbasaur.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/44_hires.png',
		nationalPokedexNumber: 1,
		evolvesTo: ['Ivysaur'],
	},
	{
		id: 'base1-44',
		name: 'Bulbasaur',
		imageUrl: 'https://images.pokemontcg.io/base1/44.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '13',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '44',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Leech Seed',
				cost: ['Grass', 'Grass'],
				convertedEnergyCost: 2,
				damage: '20',
				text:
					'Unless all damage from this attack is prevented, you may remove 1 damage counter from Bulbasaur.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/44_hires.png',
		nationalPokedexNumber: 1,
		evolvesTo: ['Ivysaur'],
	},
	{
		id: 'base1-44',
		name: 'Bulbasaur',
		imageUrl: 'https://images.pokemontcg.io/base1/44.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '13',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '44',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Leech Seed',
				cost: ['Grass', 'Grass'],
				convertedEnergyCost: 2,
				damage: '20',
				text:
					'Unless all damage from this attack is prevented, you may remove 1 damage counter from Bulbasaur.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/44_hires.png',
		nationalPokedexNumber: 1,
		evolvesTo: ['Ivysaur'],
	},
	{
		id: 'base1-44',
		name: 'Bulbasaur',
		imageUrl: 'https://images.pokemontcg.io/base1/44.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '13',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '44',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Leech Seed',
				cost: ['Grass', 'Grass'],
				convertedEnergyCost: 2,
				damage: '20',
				text:
					'Unless all damage from this attack is prevented, you may remove 1 damage counter from Bulbasaur.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/44_hires.png',
		nationalPokedexNumber: 1,
		evolvesTo: ['Ivysaur'],
	},
	{
		id: 'base1-30',
		name: 'Ivysaur',
		imageUrl: 'https://images.pokemontcg.io/base1/30.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '20',
		evolvesFrom: 'Barboach',
		hp: '60',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '30',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Vine Whip',
				cost: ['Grass', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30',
				text: '',
			},
			{
				name: 'Poisonpowder',
				cost: ['Grass', 'Grass', 'Grass'],
				convertedEnergyCost: 3,
				damage: '30',
				text: 'The Defending Pokémon is now Poisoned.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/30_hires.png',
		nationalPokedexNumber: 2,
		evolvesTo: ['Venusaur'],
	},
	{
		id: 'base1-30',
		name: 'Ivysaur',
		imageUrl: 'https://images.pokemontcg.io/base1/30.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '20',
		evolvesFrom: 'Barboach',
		hp: '60',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '30',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Vine Whip',
				cost: ['Grass', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30',
				text: '',
			},
			{
				name: 'Poisonpowder',
				cost: ['Grass', 'Grass', 'Grass'],
				convertedEnergyCost: 3,
				damage: '30',
				text: 'The Defending Pokémon is now Poisoned.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/30_hires.png',
		nationalPokedexNumber: 2,
		evolvesTo: ['Venusaur'],
	},
	{
		id: 'base1-69',
		name: 'Weedle',
		imageUrl: 'https://images.pokemontcg.io/base1/69.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '69',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Poison Sting',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, Defending Pokémon is now Poisoned.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/69_hires.png',
		nationalPokedexNumber: 13,
		evolvesTo: ['Kakuna'],
	},
	{
		id: 'base1-69',
		name: 'Weedle',
		imageUrl: 'https://images.pokemontcg.io/base1/69.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '69',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Poison Sting',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, Defending Pokémon is now Poisoned.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/69_hires.png',
		nationalPokedexNumber: 13,
		evolvesTo: ['Kakuna'],
	},
	{
		id: 'base1-69',
		name: 'Weedle',
		imageUrl: 'https://images.pokemontcg.io/base1/69.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '69',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Poison Sting',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, Defending Pokémon is now Poisoned.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/69_hires.png',
		nationalPokedexNumber: 13,
		evolvesTo: ['Kakuna'],
	},
	{
		id: 'base1-69',
		name: 'Weedle',
		imageUrl: 'https://images.pokemontcg.io/base1/69.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '69',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Poison Sting',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, Defending Pokémon is now Poisoned.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/69_hires.png',
		nationalPokedexNumber: 13,
		evolvesTo: ['Kakuna'],
	},
	{
		id: 'base1-33',
		name: 'Kakuna',
		imageUrl: 'https://images.pokemontcg.io/base1/33.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '23',
		evolvesFrom: 'Weedle',
		hp: '80',
		retreatCost: ['Colorless', 'Colorless'],
		convertedRetreatCost: 2,
		number: '33',
		artist: 'Keiji Kinebuchi',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Stiffen',
				cost: ['Colorless', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Flip a coin. If heads, prevent all damage done to Kakuna during your opponent's next turn. (Any other effects of attacks still happen.)",
			},
			{
				name: 'Poisonpowder',
				cost: ['Grass', 'Grass'],
				convertedEnergyCost: 2,
				damage: '20',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Poisoned.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/33_hires.png',
		nationalPokedexNumber: 14,
		evolvesTo: ['Beedrill'],
	},
	{
		id: 'base1-33',
		name: 'Kakuna',
		imageUrl: 'https://images.pokemontcg.io/base1/33.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '23',
		evolvesFrom: 'Weedle',
		hp: '80',
		retreatCost: ['Colorless', 'Colorless'],
		convertedRetreatCost: 2,
		number: '33',
		artist: 'Keiji Kinebuchi',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Stiffen',
				cost: ['Colorless', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Flip a coin. If heads, prevent all damage done to Kakuna during your opponent's next turn. (Any other effects of attacks still happen.)",
			},
			{
				name: 'Poisonpowder',
				cost: ['Grass', 'Grass'],
				convertedEnergyCost: 2,
				damage: '20',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Poisoned.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/33_hires.png',
		nationalPokedexNumber: 14,
		evolvesTo: ['Beedrill'],
	},
	{
		id: 'base1-17',
		name: 'Beedrill',
		imageUrl: 'https://images.pokemontcg.io/base1/17.png',
		subtype: 'Stage 2',
		supertype: 'Pokémon',
		level: '32',
		evolvesFrom: 'Kakuna',
		hp: '80',
		number: '17',
		artist: 'Ken Sugimori',
		rarity: 'Rare',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Grass'],
		attacks: [
			{
				name: 'Twineedle',
				cost: ['Colorless', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30×',
				text:
					'Flip 2 coins. This attack does 30 damage times the number of heads.',
			},
			{
				name: 'Poison Sting',
				cost: ['Grass', 'Grass', 'Grass'],
				convertedEnergyCost: 3,
				damage: '40',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Poisoned.',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Fighting',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/17_hires.png',
		nationalPokedexNumber: 15,
	},
	{
		id: 'base1-65',
		name: 'Staryu',
		imageUrl: 'https://images.pokemontcg.io/base1/65.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '15',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '65',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Slap',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '20',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/65_hires.png',
		nationalPokedexNumber: 120,
		evolvesTo: ['Starmie'],
	},
	{
		id: 'base1-65',
		name: 'Staryu',
		imageUrl: 'https://images.pokemontcg.io/base1/65.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '15',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '65',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Slap',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '20',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/65_hires.png',
		nationalPokedexNumber: 120,
		evolvesTo: ['Starmie'],
	},
	{
		id: 'base1-65',
		name: 'Staryu',
		imageUrl: 'https://images.pokemontcg.io/base1/65.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '15',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '65',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Slap',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '20',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/65_hires.png',
		nationalPokedexNumber: 120,
		evolvesTo: ['Starmie'],
	},
	{
		id: 'base1-65',
		name: 'Staryu',
		imageUrl: 'https://images.pokemontcg.io/base1/65.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '15',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '65',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Slap',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '20',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/65_hires.png',
		nationalPokedexNumber: 120,
		evolvesTo: ['Starmie'],
	},
	{
		id: 'base1-64',
		name: 'Starmie',
		imageUrl: 'https://images.pokemontcg.io/base1/64.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '28',
		evolvesFrom: 'Staryu',
		hp: '60',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '64',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Recover',
				cost: ['Water', 'Water'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					'Discard 1 Energy card to Starmie in order to use this attack. Remove all damage counters from Starmie.',
			},
			{
				name: 'Star Freeze',
				cost: ['Water', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '20',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/64_hires.png',
		nationalPokedexNumber: 121,
	},
	{
		id: 'base1-64',
		name: 'Starmie',
		imageUrl: 'https://images.pokemontcg.io/base1/64.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '28',
		evolvesFrom: 'Staryu',
		hp: '60',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '64',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Recover',
				cost: ['Water', 'Water'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					'Discard 1 Energy card to Starmie in order to use this attack. Remove all damage counters from Starmie.',
			},
			{
				name: 'Star Freeze',
				cost: ['Water', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '20',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/64_hires.png',
		nationalPokedexNumber: 121,
	},
	{
		id: 'base1-64',
		name: 'Starmie',
		imageUrl: 'https://images.pokemontcg.io/base1/64.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '28',
		evolvesFrom: 'Staryu',
		hp: '60',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '64',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Recover',
				cost: ['Water', 'Water'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					'Discard 1 Energy card to Starmie in order to use this attack. Remove all damage counters from Starmie.',
			},
			{
				name: 'Star Freeze',
				cost: ['Water', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '20',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/64_hires.png',
		nationalPokedexNumber: 121,
	},
	{
		id: 'base1-35',
		name: 'Magikarp',
		imageUrl: 'https://images.pokemontcg.io/base1/35.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '8',
		hp: '30',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '35',
		artist: 'Mitsuhiro Arita',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Tackle',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Flail',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '10×',
				text:
					'Does 10 damage times number of damage counters on Magikarp.',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/35_hires.png',
		nationalPokedexNumber: 129,
		evolvesTo: ['Gyarados'],
	},
	{
		id: 'base1-35',
		name: 'Magikarp',
		imageUrl: 'https://images.pokemontcg.io/base1/35.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '8',
		hp: '30',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '35',
		artist: 'Mitsuhiro Arita',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Tackle',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Flail',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '10×',
				text:
					'Does 10 damage times number of damage counters on Magikarp.',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/35_hires.png',
		nationalPokedexNumber: 129,
		evolvesTo: ['Gyarados'],
	},
	{
		id: 'base1-6',
		name: 'Gyarados',
		imageUrl: 'https://images.pokemontcg.io/base1/6.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '41',
		evolvesFrom: 'Magikarp',
		hp: '100',
		retreatCost: ['Colorless', 'Colorless', 'Colorless'],
		convertedRetreatCost: 3,
		number: '6',
		artist: 'Mitsuhiro Arita',
		rarity: 'Rare',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Dragon Rage',
				cost: ['Water', 'Water', 'Water'],
				convertedEnergyCost: 3,
				damage: '50',
				text: '',
			},
			{
				name: 'Bubblebeam',
				cost: ['Water', 'Water', 'Water', 'Water'],
				convertedEnergyCost: 4,
				damage: '40',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Fighting',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/6_hires.png',
		nationalPokedexNumber: 130,
	},
	{
		id: 'base1-91',
		name: 'Bill',
		imageUrl: 'https://images.pokemontcg.io/base1/91.png',
		subtype: '',
		supertype: 'Trainer',
		number: '91',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Draw 2 cards.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/91_hires.png',
	},
	{
		id: 'base1-91',
		name: 'Bill',
		imageUrl: 'https://images.pokemontcg.io/base1/91.png',
		subtype: '',
		supertype: 'Trainer',
		number: '91',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Draw 2 cards.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/91_hires.png',
	},
	{
		id: 'base1-93',
		name: 'Gust of Wind',
		imageUrl: 'https://images.pokemontcg.io/base1/93.png',
		subtype: '',
		supertype: 'Trainer',
		number: '93',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Choose 1 of your opponent's Benched Pokémon and switch it with his or her Active Pokémon.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/93_hires.png',
	},
	{
		id: 'base1-93',
		name: 'Gust of Wind',
		imageUrl: 'https://images.pokemontcg.io/base1/93.png',
		subtype: '',
		supertype: 'Trainer',
		number: '93',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Choose 1 of your opponent's Benched Pokémon and switch it with his or her Active Pokémon.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/93_hires.png',
	},
	{
		id: 'base1-94',
		name: 'Potion',
		imageUrl: 'https://images.pokemontcg.io/base1/94.png',
		subtype: '',
		supertype: 'Trainer',
		number: '94',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Remove up to 2 damage counters from 1 of your Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/94_hires.png',
	},
	{
		id: 'base1-90',
		name: 'Super Potion',
		imageUrl: 'https://images.pokemontcg.io/base1/90.png',
		subtype: '',
		supertype: 'Trainer',
		number: '90',
		artist: 'Keiji Kinebuchi',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			'Discard 1 Energy card attached to 1 of your own Pokémon in order to remove up to 4 damage counters from that Pokémon.',
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/90_hires.png',
	},
	{
		id: 'base1-90',
		name: 'Super Potion',
		imageUrl: 'https://images.pokemontcg.io/base1/90.png',
		subtype: '',
		supertype: 'Trainer',
		number: '90',
		artist: 'Keiji Kinebuchi',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			'Discard 1 Energy card attached to 1 of your own Pokémon in order to remove up to 4 damage counters from that Pokémon.',
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/90_hires.png',
	},
	{
		id: 'base1-95',
		name: 'Switch',
		imageUrl: 'https://images.pokemontcg.io/base1/95.png',
		subtype: '',
		supertype: 'Trainer',
		number: '95',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Switch 1 of your Benched Pokémon with your Active Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/95_hires.png',
	},
	{
		id: 'base1-95',
		name: 'Switch',
		imageUrl: 'https://images.pokemontcg.io/base1/95.png',
		subtype: '',
		supertype: 'Trainer',
		number: '95',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Switch 1 of your Benched Pokémon with your Active Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/95_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
];

module.exports = overgrowth;
