const powerreserve = [
	{
		id: 'base2-57',
		name: 'Nidoran♀',
		imageUrl: 'https://images.pokemontcg.io/base2/57.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '13',
		hp: '60',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '57',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Grass'],
		attacks: [
			{
				name: 'Fury Swipes',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10×',
				text:
					'Flip 3 coins. This attack does 10 damage times the number of heads.',
			},
			{
				name: 'Call for Family',
				cost: ['Grass', 'Grass'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Search your deck for a Basic Pokémon named Nidoran M or Nidoran F and put it onto your Bench. Shuffle your deck afterward. (You can't use this attack if your Bench is full.)",
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/57_hires.png',
		nationalPokedexNumber: 29,
		evolvesTo: ['Nidorina'],
	},
	{
		id: 'base2-57',
		name: 'Nidoran♀',
		imageUrl: 'https://images.pokemontcg.io/base2/57.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '13',
		hp: '60',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '57',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Grass'],
		attacks: [
			{
				name: 'Fury Swipes',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10×',
				text:
					'Flip 3 coins. This attack does 10 damage times the number of heads.',
			},
			{
				name: 'Call for Family',
				cost: ['Grass', 'Grass'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Search your deck for a Basic Pokémon named Nidoran M or Nidoran F and put it onto your Bench. Shuffle your deck afterward. (You can't use this attack if your Bench is full.)",
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/57_hires.png',
		nationalPokedexNumber: 29,
		evolvesTo: ['Nidorina'],
	},
	{
		id: 'base2-57',
		name: 'Nidoran♀',
		imageUrl: 'https://images.pokemontcg.io/base2/57.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '13',
		hp: '60',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '57',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Grass'],
		attacks: [
			{
				name: 'Fury Swipes',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10×',
				text:
					'Flip 3 coins. This attack does 10 damage times the number of heads.',
			},
			{
				name: 'Call for Family',
				cost: ['Grass', 'Grass'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Search your deck for a Basic Pokémon named Nidoran M or Nidoran F and put it onto your Bench. Shuffle your deck afterward. (You can't use this attack if your Bench is full.)",
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/57_hires.png',
		nationalPokedexNumber: 29,
		evolvesTo: ['Nidorina'],
	},
	{
		id: 'base2-57',
		name: 'Nidoran♀',
		imageUrl: 'https://images.pokemontcg.io/base2/57.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '13',
		hp: '60',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '57',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Grass'],
		attacks: [
			{
				name: 'Fury Swipes',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10×',
				text:
					'Flip 3 coins. This attack does 10 damage times the number of heads.',
			},
			{
				name: 'Call for Family',
				cost: ['Grass', 'Grass'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Search your deck for a Basic Pokémon named Nidoran M or Nidoran F and put it onto your Bench. Shuffle your deck afterward. (You can't use this attack if your Bench is full.)",
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/57_hires.png',
		nationalPokedexNumber: 29,
		evolvesTo: ['Nidorina'],
	},
	{
		id: 'base2-40',
		name: 'Nidorina',
		imageUrl: 'https://images.pokemontcg.io/base2/40.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '24',
		evolvesFrom: 'Nidoran♀',
		hp: '70',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '40',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Grass'],
		attacks: [
			{
				name: 'Supersonic',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Confused.',
			},
			{
				name: 'Double Kick',
				cost: ['Grass', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30×',
				text:
					'Flip 2 coins. This attack does 30 damage times the number of heads.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/40_hires.png',
		nationalPokedexNumber: 30,
		evolvesTo: ['Nidoqueen'],
	},
	{
		id: 'base2-40',
		name: 'Nidorina',
		imageUrl: 'https://images.pokemontcg.io/base2/40.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '24',
		evolvesFrom: 'Nidoran♀',
		hp: '70',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '40',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Grass'],
		attacks: [
			{
				name: 'Supersonic',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Confused.',
			},
			{
				name: 'Double Kick',
				cost: ['Grass', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30×',
				text:
					'Flip 2 coins. This attack does 30 damage times the number of heads.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/40_hires.png',
		nationalPokedexNumber: 30,
		evolvesTo: ['Nidoqueen'],
	},
	{
		id: 'base2-58',
		name: 'Oddish',
		imageUrl: 'https://images.pokemontcg.io/base2/58.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '8',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '58',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Grass'],
		attacks: [
			{
				name: 'Stun Spore',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
			{
				name: 'Sprout',
				cost: ['Grass', 'Grass'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Search your deck for a Basic Pokémon named Oddish and put it onto your Bench. Shuffle your deck afterward. (You can't use this attack if your Bench is full.)",
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/58_hires.png',
		nationalPokedexNumber: 43,
		evolvesTo: ['Gloom'],
	},
	{
		id: 'base2-58',
		name: 'Oddish',
		imageUrl: 'https://images.pokemontcg.io/base2/58.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '8',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '58',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Grass'],
		attacks: [
			{
				name: 'Stun Spore',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
			{
				name: 'Sprout',
				cost: ['Grass', 'Grass'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Search your deck for a Basic Pokémon named Oddish and put it onto your Bench. Shuffle your deck afterward. (You can't use this attack if your Bench is full.)",
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/58_hires.png',
		nationalPokedexNumber: 43,
		evolvesTo: ['Gloom'],
	},
	{
		id: 'base2-37',
		name: 'Gloom',
		imageUrl: 'https://images.pokemontcg.io/base2/37.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '35',
		evolvesFrom: 'Oddish',
		hp: '60',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '37',
		artist: 'Keiji Kinebuchi',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Grass'],
		attacks: [
			{
				name: 'Poisonpowder',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10',
				text: 'The Defending Pokémon is now Poisoned.',
			},
			{
				name: 'Foul Odor',
				cost: ['Grass', 'Grass'],
				convertedEnergyCost: 2,
				damage: '20',
				text:
					'Both the Defending Pokémon and Gloom are now Confused (after doing damage).',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/37_hires.png',
		nationalPokedexNumber: 44,
		evolvesTo: ['Vileplume', 'Bellossom'],
	},
	{
		id: 'base2-49',
		name: 'Bellsprout',
		imageUrl: 'https://images.pokemontcg.io/base2/49.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '11',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '49',
		artist: 'Kagemaru Himeno',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Grass'],
		attacks: [
			{
				name: 'Vine Whip',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Call for Family',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					"Search your deck for a Basic Pokémon named Bellsprout and put it onto your Bench. Shuffle your deck afterward. (You can't use this attack if your Bench is full.)",
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/49_hires.png',
		nationalPokedexNumber: 69,
		evolvesTo: ['Weepinbell'],
	},
	{
		id: 'base2-49',
		name: 'Bellsprout',
		imageUrl: 'https://images.pokemontcg.io/base2/49.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '11',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '49',
		artist: 'Kagemaru Himeno',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Grass'],
		attacks: [
			{
				name: 'Vine Whip',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Call for Family',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					"Search your deck for a Basic Pokémon named Bellsprout and put it onto your Bench. Shuffle your deck afterward. (You can't use this attack if your Bench is full.)",
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/49_hires.png',
		nationalPokedexNumber: 69,
		evolvesTo: ['Weepinbell'],
	},
	{
		id: 'base2-49',
		name: 'Bellsprout',
		imageUrl: 'https://images.pokemontcg.io/base2/49.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '11',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '49',
		artist: 'Kagemaru Himeno',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Grass'],
		attacks: [
			{
				name: 'Vine Whip',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Call for Family',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					"Search your deck for a Basic Pokémon named Bellsprout and put it onto your Bench. Shuffle your deck afterward. (You can't use this attack if your Bench is full.)",
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/49_hires.png',
		nationalPokedexNumber: 69,
		evolvesTo: ['Weepinbell'],
	},
	{
		id: 'base2-49',
		name: 'Bellsprout',
		imageUrl: 'https://images.pokemontcg.io/base2/49.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '11',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '49',
		artist: 'Kagemaru Himeno',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Grass'],
		attacks: [
			{
				name: 'Vine Whip',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Call for Family',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					"Search your deck for a Basic Pokémon named Bellsprout and put it onto your Bench. Shuffle your deck afterward. (You can't use this attack if your Bench is full.)",
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/49_hires.png',
		nationalPokedexNumber: 69,
		evolvesTo: ['Weepinbell'],
	},
	{
		id: 'base2-48',
		name: 'Weepinbell',
		imageUrl: 'https://images.pokemontcg.io/base2/48.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '28',
		evolvesFrom: 'Bellsprout',
		hp: '70',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '48',
		artist: 'Kagemaru Himeno',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Grass'],
		attacks: [
			{
				name: 'Poisonpowder',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Poisoned.',
			},
			{
				name: 'Razor Leaf',
				cost: ['Grass', 'Grass'],
				convertedEnergyCost: 2,
				damage: '30',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/48_hires.png',
		nationalPokedexNumber: 70,
		evolvesTo: ['Victreebel'],
	},
	{
		id: 'base2-48',
		name: 'Weepinbell',
		imageUrl: 'https://images.pokemontcg.io/base2/48.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '28',
		evolvesFrom: 'Bellsprout',
		hp: '70',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '48',
		artist: 'Kagemaru Himeno',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Grass'],
		attacks: [
			{
				name: 'Poisonpowder',
				cost: ['Grass'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Poisoned.',
			},
			{
				name: 'Razor Leaf',
				cost: ['Grass', 'Grass'],
				convertedEnergyCost: 2,
				damage: '30',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Fire',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/48_hires.png',
		nationalPokedexNumber: 70,
		evolvesTo: ['Victreebel'],
	},
	{
		id: 'base1-43',
		name: 'Abra',
		imageUrl: 'https://images.pokemontcg.io/base1/43.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '10',
		hp: '30',
		number: '43',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Psyshock',
				cost: ['Psychic'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/43_hires.png',
		nationalPokedexNumber: 63,
		evolvesTo: ['Kadabra'],
	},
	{
		id: 'base1-43',
		name: 'Abra',
		imageUrl: 'https://images.pokemontcg.io/base1/43.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '10',
		hp: '30',
		number: '43',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Psyshock',
				cost: ['Psychic'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/43_hires.png',
		nationalPokedexNumber: 63,
		evolvesTo: ['Kadabra'],
	},
	{
		id: 'base1-43',
		name: 'Abra',
		imageUrl: 'https://images.pokemontcg.io/base1/43.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '10',
		hp: '30',
		number: '43',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Psyshock',
				cost: ['Psychic'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/43_hires.png',
		nationalPokedexNumber: 63,
		evolvesTo: ['Kadabra'],
	},
	{
		id: 'base1-43',
		name: 'Abra',
		imageUrl: 'https://images.pokemontcg.io/base1/43.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '10',
		hp: '30',
		number: '43',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Psyshock',
				cost: ['Psychic'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/43_hires.png',
		nationalPokedexNumber: 63,
		evolvesTo: ['Kadabra'],
	},
	{
		id: 'base1-32',
		name: 'Kadabra',
		imageUrl: 'https://images.pokemontcg.io/base1/32.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '38',
		evolvesFrom: 'Abra',
		hp: '60',
		retreatCost: ['Colorless', 'Colorless', 'Colorless'],
		convertedRetreatCost: 3,
		number: '32',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Recover',
				cost: ['Psychic', 'Psychic'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					'Discard 1 Energy card attached to Kadabra in order use this attack. Remove all damage counters from Kadabra.',
			},
			{
				name: 'Super Psy',
				cost: ['Psychic', 'Psychic', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '50',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/32_hires.png',
		nationalPokedexNumber: 64,
		evolvesTo: ['Alakazam'],
	},
	{
		id: 'base1-32',
		name: 'Kadabra',
		imageUrl: 'https://images.pokemontcg.io/base1/32.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '38',
		evolvesFrom: 'Abra',
		hp: '60',
		retreatCost: ['Colorless', 'Colorless', 'Colorless'],
		convertedRetreatCost: 3,
		number: '32',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Recover',
				cost: ['Psychic', 'Psychic'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					'Discard 1 Energy card attached to Kadabra in order use this attack. Remove all damage counters from Kadabra.',
			},
			{
				name: 'Super Psy',
				cost: ['Psychic', 'Psychic', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '50',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/32_hires.png',
		nationalPokedexNumber: 64,
		evolvesTo: ['Alakazam'],
	},
	{
		id: 'base1-31',
		name: 'Jynx',
		imageUrl: 'https://images.pokemontcg.io/base1/31.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '23',
		hp: '70',
		retreatCost: ['Colorless', 'Colorless'],
		convertedRetreatCost: 2,
		number: '31',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Doubleslap',
				cost: ['Psychic'],
				convertedEnergyCost: 1,
				damage: '10×',
				text:
					'Flip 2 coins. This attack does 10 damage times the number of heads.',
			},
			{
				name: 'Meditate',
				cost: ['Psychic', 'Psychic', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '20+',
				text:
					'Does 20 damage plus 10 more damage for each damage counter on the Defending Pokémon.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/31_hires.png',
		nationalPokedexNumber: 124,
	},
	{
		id: 'base2-5',
		name: 'Kangaskhan',
		imageUrl: 'https://images.pokemontcg.io/base2/5.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '40',
		hp: '90',
		retreatCost: ['Colorless', 'Colorless', 'Colorless'],
		convertedRetreatCost: 3,
		number: '5',
		artist: 'Mitsuhiro Arita',
		rarity: 'Rare',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Colorless'],
		attacks: [
			{
				name: 'Fetch',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '',
				text: 'Draw a card.',
			},
			{
				name: 'Comet Punch',
				cost: ['Colorless', 'Colorless', 'Colorless', 'Colorless'],
				convertedEnergyCost: 4,
				damage: '20×',
				text:
					'Flip 4 coins. This attack does 20 damage times the number of heads.',
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Psychic',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/5_hires.png',
		nationalPokedexNumber: 115,
	},

	{
		id: 'base1-91',
		name: 'Bill',
		imageUrl: 'https://images.pokemontcg.io/base1/91.png',
		subtype: '',
		supertype: 'Trainer',
		number: '91',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Draw 2 cards.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/91_hires.png',
	},
	{
		id: 'base1-91',
		name: 'Bill',
		imageUrl: 'https://images.pokemontcg.io/base1/91.png',
		subtype: '',
		supertype: 'Trainer',
		number: '91',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Draw 2 cards.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/91_hires.png',
	},
	{
		id: 'base1-93',
		name: 'Gust of Wind',
		imageUrl: 'https://images.pokemontcg.io/base1/93.png',
		subtype: '',
		supertype: 'Trainer',
		number: '93',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Choose 1 of your opponent's Benched Pokémon and switch it with his or her Active Pokémon.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/93_hires.png',
	},
	{
		id: 'base1-93',
		name: 'Gust of Wind',
		imageUrl: 'https://images.pokemontcg.io/base1/93.png',
		subtype: '',
		supertype: 'Trainer',
		number: '93',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Choose 1 of your opponent's Benched Pokémon and switch it with his or her Active Pokémon.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/93_hires.png',
	},
	{
		id: 'base1-87',
		name: 'Pokédex',
		imageUrl: 'https://images.pokemontcg.io/base1/87.png',
		subtype: '',
		supertype: 'Trainer',
		number: '87',
		artist: 'Keiji Kinebuchi',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			'Look at up to 5 cards from the top of your deck and rearrange them as you like.',
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/87_hires.png',
	},
	{
		id: 'base1-94',
		name: 'Potion',
		imageUrl: 'https://images.pokemontcg.io/base1/94.png',
		subtype: '',
		supertype: 'Trainer',
		number: '94',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Remove up to 2 damage counters from 1 of your Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/94_hires.png',
	},
	{
		id: 'base1-94',
		name: 'Potion',
		imageUrl: 'https://images.pokemontcg.io/base1/94.png',
		subtype: '',
		supertype: 'Trainer',
		number: '94',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Remove up to 2 damage counters from 1 of your Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/94_hires.png',
	},
	{
		id: 'base1-94',
		name: 'Potion',
		imageUrl: 'https://images.pokemontcg.io/base1/94.png',
		subtype: '',
		supertype: 'Trainer',
		number: '94',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Remove up to 2 damage counters from 1 of your Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/94_hires.png',
	},
	{
		id: 'base1-95',
		name: 'Switch',
		imageUrl: 'https://images.pokemontcg.io/base1/95.png',
		subtype: '',
		supertype: 'Trainer',
		number: '95',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Switch 1 of your Benched Pokémon with your Active Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/95_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-99',
		name: 'Grass Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/99.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '99',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/99_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
];

module.exports = powerreserve;
