const waterblast = [
	{
		id: 'base1-59',
		name: 'Poliwag',
		imageUrl: 'https://images.pokemontcg.io/base1/59.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '13',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '59',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Water Gun',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '10+',
				text:
					"Does 10 damage plus 10 damage for each Energy attached to Poliwag but not used to pay for this attack's Energy cost. Extra Energy after the end don't count.",
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/59_hires.png',
		nationalPokedexNumber: 60,
		evolvesTo: ['Poliwhirl'],
	},
	{
		id: 'base1-59',
		name: 'Poliwag',
		imageUrl: 'https://images.pokemontcg.io/base1/59.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '13',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '59',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Water Gun',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '10+',
				text:
					"Does 10 damage plus 10 damage for each Energy attached to Poliwag but not used to pay for this attack's Energy cost. Extra Energy after the end don't count.",
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/59_hires.png',
		nationalPokedexNumber: 60,
		evolvesTo: ['Poliwhirl'],
	},
	{
		id: 'base1-59',
		name: 'Poliwag',
		imageUrl: 'https://images.pokemontcg.io/base1/59.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '13',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '59',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Water Gun',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '10+',
				text:
					"Does 10 damage plus 10 damage for each Energy attached to Poliwag but not used to pay for this attack's Energy cost. Extra Energy after the end don't count.",
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/59_hires.png',
		nationalPokedexNumber: 60,
		evolvesTo: ['Poliwhirl'],
	},
	{
		id: 'base1-59',
		name: 'Poliwag',
		imageUrl: 'https://images.pokemontcg.io/base1/59.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '13',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '59',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Water Gun',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '10+',
				text:
					"Does 10 damage plus 10 damage for each Energy attached to Poliwag but not used to pay for this attack's Energy cost. Extra Energy after the end don't count.",
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/59_hires.png',
		nationalPokedexNumber: 60,
		evolvesTo: ['Poliwhirl'],
	},
	{
		id: 'base1-38',
		name: 'Poliwhirl',
		imageUrl: 'https://images.pokemontcg.io/base1/38.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '28',
		evolvesFrom: 'Poliwag',
		hp: '60',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '38',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Amnesia',
				cost: ['Water', 'Water'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					'Choose 1 of defenders attacks. Defender cannot use that attack next turn.',
			},
			{
				name: 'Doubleslap',
				cost: ['Water', 'Water', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30×',
				text:
					'Flip 2 coins. This attack does 30 damage times number of heads.',
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/38_hires.png',
		nationalPokedexNumber: 61,
		evolvesTo: ['Poliwrath', 'Politoed'],
	},
	{
		id: 'base1-38',
		name: 'Poliwhirl',
		imageUrl: 'https://images.pokemontcg.io/base1/38.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '28',
		evolvesFrom: 'Poliwag',
		hp: '60',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '38',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Amnesia',
				cost: ['Water', 'Water'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					'Choose 1 of defenders attacks. Defender cannot use that attack next turn.',
			},
			{
				name: 'Doubleslap',
				cost: ['Water', 'Water', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30×',
				text:
					'Flip 2 coins. This attack does 30 damage times number of heads.',
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/38_hires.png',
		nationalPokedexNumber: 61,
		evolvesTo: ['Poliwrath', 'Politoed'],
	},
	{
		id: 'base1-41',
		name: 'Seel',
		imageUrl: 'https://images.pokemontcg.io/base1/41.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '60',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '41',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Water'],
		attacks: [
			{
				name: 'Headbutt',
				cost: ['Water'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/41_hires.png',
		nationalPokedexNumber: 86,
		evolvesTo: ['Dewgong'],
	},
	{
		id: 'base2-12',
		name: 'Vaporeon',
		imageUrl: 'https://images.pokemontcg.io/base2/12.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '42',
		evolvesFrom: 'Eevee',
		hp: '80',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '12',
		artist: 'Kagemaru Himeno',
		rarity: 'Rare',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Water'],
		attacks: [
			{
				name: 'Quick Attack',
				cost: ['Colorless', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '10+',
				text:
					'Flip a coin. If heads, this attack does 10 damage plus 20 more damage; if tails, this attack does 10 damage.',
			},
			{
				name: 'Water Gun',
				cost: ['Water', 'Water', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30+',
				text:
					"Does 30 damage plus 10 more damage for each Energy attached to Vaporeon but not used to pay for this attack's Energy cost. Extra Energy after the 2nd doesn't count.",
			},
		],
		weaknesses: [
			{
				type: 'Lightning',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/12_hires.png',
		nationalPokedexNumber: 134,
	},
	{
		id: 'base1-52',
		name: 'Machop',
		imageUrl: 'https://images.pokemontcg.io/base1/52.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '20',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '52',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Low Kick',
				cost: ['Fighting'],
				convertedEnergyCost: 1,
				damage: '20',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/52_hires.png',
		nationalPokedexNumber: 66,
		evolvesTo: ['Machoke'],
	},
	{
		id: 'base1-52',
		name: 'Machop',
		imageUrl: 'https://images.pokemontcg.io/base1/52.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '20',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '52',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Low Kick',
				cost: ['Fighting'],
				convertedEnergyCost: 1,
				damage: '20',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/52_hires.png',
		nationalPokedexNumber: 66,
		evolvesTo: ['Machoke'],
	},
	{
		id: 'base2-61',
		name: 'Rhyhorn',
		imageUrl: 'https://images.pokemontcg.io/base2/61.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '18',
		hp: '70',
		retreatCost: ['Colorless', 'Colorless', 'Colorless'],
		convertedRetreatCost: 3,
		number: '61',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Leer',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					"Flip a coin. If heads, the Defending Pokémon can't attack Rhyhorn during your opponent's next turn. (Benching either Pokémon ends this effect.)",
			},
			{
				name: 'Horn Attack',
				cost: ['Fighting', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Lightning',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/61_hires.png',
		nationalPokedexNumber: 111,
		evolvesTo: ['Rhydon'],
	},
	{
		id: 'base2-61',
		name: 'Rhyhorn',
		imageUrl: 'https://images.pokemontcg.io/base2/61.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '18',
		hp: '70',
		retreatCost: ['Colorless', 'Colorless', 'Colorless'],
		convertedRetreatCost: 3,
		number: '61',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Leer',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					"Flip a coin. If heads, the Defending Pokémon can't attack Rhyhorn during your opponent's next turn. (Benching either Pokémon ends this effect.)",
			},
			{
				name: 'Horn Attack',
				cost: ['Fighting', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Lightning',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/61_hires.png',
		nationalPokedexNumber: 111,
		evolvesTo: ['Rhydon'],
	},
	{
		id: 'base2-61',
		name: 'Rhyhorn',
		imageUrl: 'https://images.pokemontcg.io/base2/61.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '18',
		hp: '70',
		retreatCost: ['Colorless', 'Colorless', 'Colorless'],
		convertedRetreatCost: 3,
		number: '61',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Leer',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					"Flip a coin. If heads, the Defending Pokémon can't attack Rhyhorn during your opponent's next turn. (Benching either Pokémon ends this effect.)",
			},
			{
				name: 'Horn Attack',
				cost: ['Fighting', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Lightning',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/61_hires.png',
		nationalPokedexNumber: 111,
		evolvesTo: ['Rhydon'],
	},
	{
		id: 'base2-45',
		name: 'Rhydon',
		imageUrl: 'https://images.pokemontcg.io/base2/45.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '48',
		evolvesFrom: 'Rhyhorn',
		hp: '100',
		retreatCost: ['Colorless', 'Colorless', 'Colorless'],
		convertedRetreatCost: 3,
		number: '45',
		artist: 'Kagemaru Himeno',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Fighting'],
		attacks: [
			{
				name: 'Horn Attack',
				cost: ['Fighting', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30',
				text: '',
			},
			{
				name: 'Ram',
				cost: ['Fighting', 'Fighting', 'Fighting', 'Fighting'],
				convertedEnergyCost: 4,
				damage: '50',
				text:
					'Rhydon does 20 damage to itself. If your opponent has any Benched Pokémon, he or she chooses 1 of them and switches it with the Defending Pokémon. (Do the damage before switching the Pokémon. Switch the Pokémon even if Rhydon is knocked out.)',
			},
		],
		weaknesses: [
			{
				type: 'Grass',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Lightning',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/45_hires.png',
		nationalPokedexNumber: 112,
		evolvesTo: ['Rhyperior'],
	},
	{
		id: 'base2-56',
		name: 'Meowth',
		imageUrl: 'https://images.pokemontcg.io/base2/56.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '15',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '56',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Colorless'],
		attacks: [
			{
				name: 'Pay Day',
				cost: ['Colorless', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '10',
				text: 'Flip a coin. If heads, draw a card.',
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Psychic',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/56_hires.png',
		nationalPokedexNumber: 52,
		evolvesTo: ['Persian'],
	},
	{
		id: 'base2-56',
		name: 'Meowth',
		imageUrl: 'https://images.pokemontcg.io/base2/56.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '15',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '56',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Colorless'],
		attacks: [
			{
				name: 'Pay Day',
				cost: ['Colorless', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '10',
				text: 'Flip a coin. If heads, draw a card.',
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Psychic',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/56_hires.png',
		nationalPokedexNumber: 52,
		evolvesTo: ['Persian'],
	},
	{
		id: 'base2-56',
		name: 'Meowth',
		imageUrl: 'https://images.pokemontcg.io/base2/56.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '15',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '56',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Colorless'],
		attacks: [
			{
				name: 'Pay Day',
				cost: ['Colorless', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '10',
				text: 'Flip a coin. If heads, draw a card.',
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Psychic',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/56_hires.png',
		nationalPokedexNumber: 52,
		evolvesTo: ['Persian'],
	},
	{
		id: 'base2-56',
		name: 'Meowth',
		imageUrl: 'https://images.pokemontcg.io/base2/56.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '15',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '56',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Colorless'],
		attacks: [
			{
				name: 'Pay Day',
				cost: ['Colorless', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '10',
				text: 'Flip a coin. If heads, draw a card.',
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Psychic',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/56_hires.png',
		nationalPokedexNumber: 52,
		evolvesTo: ['Persian'],
	},
	{
		id: 'base2-42',
		name: 'Persian',
		imageUrl: 'https://images.pokemontcg.io/base2/42.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '25',
		evolvesFrom: 'Meowth',
		hp: '70',
		convertedRetreatCost: 0,
		number: '42',
		artist: 'Kagemaru Himeno',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Colorless'],
		attacks: [
			{
				name: 'Scratch',
				cost: ['Colorless', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '20',
				text: '',
			},
			{
				name: 'Pounce',
				cost: ['Colorless', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30',
				text:
					"If the Defending Pokémon attacks Persian during your opponent's next turn, any damage done by the attack is reduce by 10 (after applying Weakness and Resistance). (Benching either Pokémon ends this effect.)",
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Psychic',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/42_hires.png',
		nationalPokedexNumber: 53,
	},
	{
		id: 'base2-42',
		name: 'Persian',
		imageUrl: 'https://images.pokemontcg.io/base2/42.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '25',
		evolvesFrom: 'Meowth',
		hp: '70',
		convertedRetreatCost: 0,
		number: '42',
		artist: 'Kagemaru Himeno',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Colorless'],
		attacks: [
			{
				name: 'Scratch',
				cost: ['Colorless', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '20',
				text: '',
			},
			{
				name: 'Pounce',
				cost: ['Colorless', 'Colorless', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '30',
				text:
					"If the Defending Pokémon attacks Persian during your opponent's next turn, any damage done by the attack is reduce by 10 (after applying Weakness and Resistance). (Benching either Pokémon ends this effect.)",
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Psychic',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/42_hires.png',
		nationalPokedexNumber: 53,
	},
	{
		id: 'base2-51',
		name: 'Eevee',
		imageUrl: 'https://images.pokemontcg.io/base2/51.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '51',
		artist: 'Kagemaru Himeno',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Colorless'],
		attacks: [
			{
				name: 'Tail Wag',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					"Flip a coin. If heads, the Defending Pokémon can't attack Eevee during your opponent's next turn. (Benching either Pokémon ends this effect.)",
			},
			{
				name: 'Quick Attack',
				cost: ['Colorless', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '10+',
				text:
					'Flip a coin. If heads, this attack does 10 damage plus 20 more damage; if tails, this attack does 10 damage.',
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Psychic',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/51_hires.png',
		nationalPokedexNumber: 133,
		evolvesTo: [
			'Vaporeon',
			'Jolteon',
			'Flareon',
			'Sylveon',
			'Espeon',
			'Umbreon',
			'Leafeon',
			'Glaceon',
		],
	},
	{
		id: 'base2-51',
		name: 'Eevee',
		imageUrl: 'https://images.pokemontcg.io/base2/51.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '51',
		artist: 'Kagemaru Himeno',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Colorless'],
		attacks: [
			{
				name: 'Tail Wag',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					"Flip a coin. If heads, the Defending Pokémon can't attack Eevee during your opponent's next turn. (Benching either Pokémon ends this effect.)",
			},
			{
				name: 'Quick Attack',
				cost: ['Colorless', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '10+',
				text:
					'Flip a coin. If heads, this attack does 10 damage plus 20 more damage; if tails, this attack does 10 damage.',
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Psychic',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/51_hires.png',
		nationalPokedexNumber: 133,
		evolvesTo: [
			'Vaporeon',
			'Jolteon',
			'Flareon',
			'Sylveon',
			'Espeon',
			'Umbreon',
			'Leafeon',
			'Glaceon',
		],
	},
	{
		id: 'base2-51',
		name: 'Eevee',
		imageUrl: 'https://images.pokemontcg.io/base2/51.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '51',
		artist: 'Kagemaru Himeno',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Colorless'],
		attacks: [
			{
				name: 'Tail Wag',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					"Flip a coin. If heads, the Defending Pokémon can't attack Eevee during your opponent's next turn. (Benching either Pokémon ends this effect.)",
			},
			{
				name: 'Quick Attack',
				cost: ['Colorless', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '10+',
				text:
					'Flip a coin. If heads, this attack does 10 damage plus 20 more damage; if tails, this attack does 10 damage.',
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Psychic',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/51_hires.png',
		nationalPokedexNumber: 133,
		evolvesTo: [
			'Vaporeon',
			'Jolteon',
			'Flareon',
			'Sylveon',
			'Espeon',
			'Umbreon',
			'Leafeon',
			'Glaceon',
		],
	},
	{
		id: 'base2-51',
		name: 'Eevee',
		imageUrl: 'https://images.pokemontcg.io/base2/51.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '50',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '51',
		artist: 'Kagemaru Himeno',
		rarity: 'Common',
		series: 'Base',
		set: 'Jungle',
		setCode: 'base2',
		types: ['Colorless'],
		attacks: [
			{
				name: 'Tail Wag',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					"Flip a coin. If heads, the Defending Pokémon can't attack Eevee during your opponent's next turn. (Benching either Pokémon ends this effect.)",
			},
			{
				name: 'Quick Attack',
				cost: ['Colorless', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '10+',
				text:
					'Flip a coin. If heads, this attack does 10 damage plus 20 more damage; if tails, this attack does 10 damage.',
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		resistances: [
			{
				type: 'Psychic',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base2/51_hires.png',
		nationalPokedexNumber: 133,
		evolvesTo: [
			'Vaporeon',
			'Jolteon',
			'Flareon',
			'Sylveon',
			'Espeon',
			'Umbreon',
			'Leafeon',
			'Glaceon',
		],
	},
	{
		id: 'base1-93',
		name: 'Gust of Wind',
		imageUrl: 'https://images.pokemontcg.io/base1/93.png',
		subtype: '',
		supertype: 'Trainer',
		number: '93',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Choose 1 of your opponent's Benched Pokémon and switch it with his or her Active Pokémon.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/93_hires.png',
	},
	{
		id: 'base1-93',
		name: 'Gust of Wind',
		imageUrl: 'https://images.pokemontcg.io/base1/93.png',
		subtype: '',
		supertype: 'Trainer',
		number: '93',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Choose 1 of your opponent's Benched Pokémon and switch it with his or her Active Pokémon.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/93_hires.png',
	},
	{
		id: 'base1-94',
		name: 'Potion',
		imageUrl: 'https://images.pokemontcg.io/base1/94.png',
		subtype: '',
		supertype: 'Trainer',
		number: '94',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Remove up to 2 damage counters from 1 of your Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/94_hires.png',
	},
	{
		id: 'base1-94',
		name: 'Potion',
		imageUrl: 'https://images.pokemontcg.io/base1/94.png',
		subtype: '',
		supertype: 'Trainer',
		number: '94',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Remove up to 2 damage counters from 1 of your Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/94_hires.png',
	},
	{
		id: 'base1-88',
		name: 'Professor Oak',
		imageUrl: 'https://images.pokemontcg.io/base1/88.png',
		subtype: '',
		supertype: 'Trainer',
		number: '88',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Discard your hand, then draw 7 cards.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/88_hires.png',
	},
	{
		id: 'base1-90',
		name: 'Super Potion',
		imageUrl: 'https://images.pokemontcg.io/base1/90.png',
		subtype: '',
		supertype: 'Trainer',
		number: '90',
		artist: 'Keiji Kinebuchi',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			'Discard 1 Energy card attached to 1 of your own Pokémon in order to remove up to 4 damage counters from that Pokémon.',
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/90_hires.png',
	},
	{
		id: 'base1-90',
		name: 'Super Potion',
		imageUrl: 'https://images.pokemontcg.io/base1/90.png',
		subtype: '',
		supertype: 'Trainer',
		number: '90',
		artist: 'Keiji Kinebuchi',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			'Discard 1 Energy card attached to 1 of your own Pokémon in order to remove up to 4 damage counters from that Pokémon.',
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/90_hires.png',
	},
	{
		id: 'base1-95',
		name: 'Switch',
		imageUrl: 'https://images.pokemontcg.io/base1/95.png',
		subtype: '',
		supertype: 'Trainer',
		number: '95',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Switch 1 of your Benched Pokémon with your Active Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/95_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-102',
		name: 'Water Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/102.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '102',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/102_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
	{
		id: 'base1-97',
		name: 'Fighting Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/97.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '97',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/97_hires.png',
	},
];

module.exports = waterblast;
