const zap = [
	{
		id: 'base1-58',
		name: 'Pikachu',
		imageUrl: 'https://images.pokemontcg.io/base1/58.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '58',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Lightning'],
		attacks: [
			{
				name: 'Gnaw',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Thunder Jolt',
				cost: ['Lightning', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '30',
				text:
					'Flip a coin. If tails, Pikachu does 10 damage to itself.',
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/58_hires.png',
		nationalPokedexNumber: 25,
		evolvesTo: ['Raichu'],
	},
	{
		id: 'base1-58',
		name: 'Pikachu',
		imageUrl: 'https://images.pokemontcg.io/base1/58.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '58',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Lightning'],
		attacks: [
			{
				name: 'Gnaw',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Thunder Jolt',
				cost: ['Lightning', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '30',
				text:
					'Flip a coin. If tails, Pikachu does 10 damage to itself.',
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/58_hires.png',
		nationalPokedexNumber: 25,
		evolvesTo: ['Raichu'],
	},
	{
		id: 'base1-58',
		name: 'Pikachu',
		imageUrl: 'https://images.pokemontcg.io/base1/58.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '58',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Lightning'],
		attacks: [
			{
				name: 'Gnaw',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Thunder Jolt',
				cost: ['Lightning', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '30',
				text:
					'Flip a coin. If tails, Pikachu does 10 damage to itself.',
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/58_hires.png',
		nationalPokedexNumber: 25,
		evolvesTo: ['Raichu'],
	},
	{
		id: 'base1-58',
		name: 'Pikachu',
		imageUrl: 'https://images.pokemontcg.io/base1/58.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '12',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '58',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Lightning'],
		attacks: [
			{
				name: 'Gnaw',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Thunder Jolt',
				cost: ['Lightning', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '30',
				text:
					'Flip a coin. If tails, Pikachu does 10 damage to itself.',
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/58_hires.png',
		nationalPokedexNumber: 25,
		evolvesTo: ['Raichu'],
	},
	{
		id: 'base1-53',
		name: 'Magnemite',
		imageUrl: 'https://images.pokemontcg.io/base1/53.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '13',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '53',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Lightning'],
		attacks: [
			{
				name: 'Thunder Wave',
				cost: ['Lightning'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
			{
				name: 'Selfdestruct',
				cost: ['Lightning', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '40',
				text:
					"Does 10 damage to each Pokémon on each player's Bench. (Don't apply Weakness and Resistance for Benched Pokémon.) Magnemite does 40 damage to itself.",
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/53_hires.png',
		nationalPokedexNumber: 81,
		evolvesTo: ['Magneton'],
	},
	{
		id: 'base1-53',
		name: 'Magnemite',
		imageUrl: 'https://images.pokemontcg.io/base1/53.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '13',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '53',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Lightning'],
		attacks: [
			{
				name: 'Thunder Wave',
				cost: ['Lightning'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
			{
				name: 'Selfdestruct',
				cost: ['Lightning', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '40',
				text:
					"Does 10 damage to each Pokémon on each player's Bench. (Don't apply Weakness and Resistance for Benched Pokémon.) Magnemite does 40 damage to itself.",
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/53_hires.png',
		nationalPokedexNumber: 81,
		evolvesTo: ['Magneton'],
	},
	{
		id: 'base1-53',
		name: 'Magnemite',
		imageUrl: 'https://images.pokemontcg.io/base1/53.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '13',
		hp: '40',
		retreatCost: ['Colorless'],
		convertedRetreatCost: 1,
		number: '53',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Lightning'],
		attacks: [
			{
				name: 'Thunder Wave',
				cost: ['Lightning'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
			{
				name: 'Selfdestruct',
				cost: ['Lightning', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '40',
				text:
					"Does 10 damage to each Pokémon on each player's Bench. (Don't apply Weakness and Resistance for Benched Pokémon.) Magnemite does 40 damage to itself.",
			},
		],
		weaknesses: [
			{
				type: 'Fighting',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/53_hires.png',
		nationalPokedexNumber: 81,
		evolvesTo: ['Magneton'],
	},
	{
		id: 'base1-43',
		name: 'Abra',
		imageUrl: 'https://images.pokemontcg.io/base1/43.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '10',
		hp: '30',
		number: '43',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Psyshock',
				cost: ['Psychic'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/43_hires.png',
		nationalPokedexNumber: 63,
		evolvesTo: ['Kadabra'],
	},
	{
		id: 'base1-43',
		name: 'Abra',
		imageUrl: 'https://images.pokemontcg.io/base1/43.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '10',
		hp: '30',
		number: '43',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Psyshock',
				cost: ['Psychic'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/43_hires.png',
		nationalPokedexNumber: 63,
		evolvesTo: ['Kadabra'],
	},
	{
		id: 'base1-43',
		name: 'Abra',
		imageUrl: 'https://images.pokemontcg.io/base1/43.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '10',
		hp: '30',
		number: '43',
		artist: 'Mitsuhiro Arita',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Psyshock',
				cost: ['Psychic'],
				convertedEnergyCost: 1,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/43_hires.png',
		nationalPokedexNumber: 63,
		evolvesTo: ['Kadabra'],
	},
	{
		id: 'base1-32',
		name: 'Kadabra',
		imageUrl: 'https://images.pokemontcg.io/base1/32.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '38',
		evolvesFrom: 'Abra',
		hp: '60',
		retreatCost: ['Colorless', 'Colorless', 'Colorless'],
		convertedRetreatCost: 3,
		number: '32',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Recover',
				cost: ['Psychic', 'Psychic'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					'Discard 1 Energy card attached to Kadabra in order use this attack. Remove all damage counters from Kadabra.',
			},
			{
				name: 'Super Psy',
				cost: ['Psychic', 'Psychic', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '50',
				text: '',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/32_hires.png',
		nationalPokedexNumber: 64,
		evolvesTo: ['Alakazam'],
	},
	{
		id: 'base1-50',
		name: 'Gastly',
		imageUrl: 'https://images.pokemontcg.io/base1/50.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '8',
		hp: '30',
		number: '50',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Sleeping Gas',
				cost: ['Psychic'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Asleep.',
			},
			{
				name: 'Destiny Bond',
				cost: ['Psychic', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Discard 1 Energy card attached to Gastly in order to use this attack. If a Pokémon Knocks Out Gastly during your opponent's next turn, Knock Out that Pokémon.",
			},
		],
		resistances: [
			{
				type: 'Fighting',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/50_hires.png',
		nationalPokedexNumber: 92,
		evolvesTo: ['Haunter'],
	},
	{
		id: 'base1-50',
		name: 'Gastly',
		imageUrl: 'https://images.pokemontcg.io/base1/50.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '8',
		hp: '30',
		number: '50',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Sleeping Gas',
				cost: ['Psychic'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Asleep.',
			},
			{
				name: 'Destiny Bond',
				cost: ['Psychic', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Discard 1 Energy card attached to Gastly in order to use this attack. If a Pokémon Knocks Out Gastly during your opponent's next turn, Knock Out that Pokémon.",
			},
		],
		resistances: [
			{
				type: 'Fighting',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/50_hires.png',
		nationalPokedexNumber: 92,
		evolvesTo: ['Haunter'],
	},
	{
		id: 'base1-50',
		name: 'Gastly',
		imageUrl: 'https://images.pokemontcg.io/base1/50.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '8',
		hp: '30',
		number: '50',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Sleeping Gas',
				cost: ['Psychic'],
				convertedEnergyCost: 1,
				damage: '',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Asleep.',
			},
			{
				name: 'Destiny Bond',
				cost: ['Psychic', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Discard 1 Energy card attached to Gastly in order to use this attack. If a Pokémon Knocks Out Gastly during your opponent's next turn, Knock Out that Pokémon.",
			},
		],
		resistances: [
			{
				type: 'Fighting',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/50_hires.png',
		nationalPokedexNumber: 92,
		evolvesTo: ['Haunter'],
	},
	{
		id: 'base3-21',
		name: 'Haunter',
		imageUrl: 'https://images.pokemontcg.io/base3/21.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '17',
		evolvesFrom: 'Gastly',
		ability: {
			name: 'Transparency',
			text:
				'Whenever an attack does anything to Haunter, flip a coin. If heads, prevent all effects of that attack, including damage, done to Haunter. This power stops working while Haunter is Asleep.',
			type: 'Pokémon Power',
		},
		hp: '50',
		convertedRetreatCost: 0,
		number: '21',
		artist: 'Ken Sugimori',
		rarity: 'Rare',
		series: 'Base',
		set: 'Fossil',
		setCode: 'base3',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Nightmare',
				cost: ['Psychic', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '10',
				text: 'The Defending Pokémon is now Asleep.',
			},
		],
		resistances: [
			{
				type: 'Fighting',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base3/21_hires.png',
		nationalPokedexNumber: 93,
		evolvesTo: ['Gengar'],
	},
	{
		id: 'base3-21',
		name: 'Haunter',
		imageUrl: 'https://images.pokemontcg.io/base3/21.png',
		subtype: 'Stage 1',
		supertype: 'Pokémon',
		level: '17',
		evolvesFrom: 'Gastly',
		ability: {
			name: 'Transparency',
			text:
				'Whenever an attack does anything to Haunter, flip a coin. If heads, prevent all effects of that attack, including damage, done to Haunter. This power stops working while Haunter is Asleep.',
			type: 'Pokémon Power',
		},
		hp: '50',
		convertedRetreatCost: 0,
		number: '21',
		artist: 'Ken Sugimori',
		rarity: 'Rare',
		series: 'Base',
		set: 'Fossil',
		setCode: 'base3',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Nightmare',
				cost: ['Psychic', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '10',
				text: 'The Defending Pokémon is now Asleep.',
			},
		],
		resistances: [
			{
				type: 'Fighting',
				value: '-30',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base3/21_hires.png',
		nationalPokedexNumber: 93,
		evolvesTo: ['Gengar'],
	},
	{
		id: 'base1-49',
		name: 'Drowzee',
		imageUrl: 'https://images.pokemontcg.io/base1/49.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '10',
		hp: '50',
		number: '49',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Pound',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Confuse Ray',
				cost: ['Psychic', 'Psychic'],
				convertedEnergyCost: 2,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Confused.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/49_hires.png',
		nationalPokedexNumber: 96,
		evolvesTo: ['Hypno'],
	},
	{
		id: 'base1-49',
		name: 'Drowzee',
		imageUrl: 'https://images.pokemontcg.io/base1/49.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '10',
		hp: '50',
		number: '49',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Pound',
				cost: ['Colorless'],
				convertedEnergyCost: 1,
				damage: '10',
				text: '',
			},
			{
				name: 'Confuse Ray',
				cost: ['Psychic', 'Psychic'],
				convertedEnergyCost: 2,
				damage: '10',
				text:
					'Flip a coin. If heads, the Defending Pokémon is now Confused.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/49_hires.png',
		nationalPokedexNumber: 96,
		evolvesTo: ['Hypno'],
	},
	{
		id: 'base1-31',
		name: 'Jynx',
		imageUrl: 'https://images.pokemontcg.io/base1/31.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '23',
		hp: '70',
		retreatCost: ['Colorless', 'Colorless'],
		convertedRetreatCost: 2,
		number: '31',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Doubleslap',
				cost: ['Psychic'],
				convertedEnergyCost: 1,
				damage: '10×',
				text:
					'Flip 2 coins. This attack does 10 damage times the number of heads.',
			},
			{
				name: 'Meditate',
				cost: ['Psychic', 'Psychic', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '20+',
				text:
					'Does 20 damage plus 10 more damage for each damage counter on the Defending Pokémon.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/31_hires.png',
		nationalPokedexNumber: 124,
	},
	{
		id: 'base1-31',
		name: 'Jynx',
		imageUrl: 'https://images.pokemontcg.io/base1/31.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '23',
		hp: '70',
		retreatCost: ['Colorless', 'Colorless'],
		convertedRetreatCost: 2,
		number: '31',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Doubleslap',
				cost: ['Psychic'],
				convertedEnergyCost: 1,
				damage: '10×',
				text:
					'Flip 2 coins. This attack does 10 damage times the number of heads.',
			},
			{
				name: 'Meditate',
				cost: ['Psychic', 'Psychic', 'Colorless'],
				convertedEnergyCost: 3,
				damage: '20+',
				text:
					'Does 20 damage plus 10 more damage for each damage counter on the Defending Pokémon.',
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/31_hires.png',
		nationalPokedexNumber: 124,
	},
	{
		id: 'base1-10',
		name: 'Mewtwo',
		imageUrl: 'https://images.pokemontcg.io/base1/10.png',
		subtype: 'Basic',
		supertype: 'Pokémon',
		level: '53',
		hp: '60',
		retreatCost: ['Colorless', 'Colorless', 'Colorless'],
		convertedRetreatCost: 3,
		number: '10',
		artist: 'Ken Sugimori',
		rarity: 'Rare',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		types: ['Psychic'],
		attacks: [
			{
				name: 'Psychic',
				cost: ['Psychic', 'Colorless'],
				convertedEnergyCost: 2,
				damage: '10+',
				text:
					'Does 10 damage plus 10 more damage for each Energy card attached to the Defending Pokémon.',
			},
			{
				name: 'Barrier',
				cost: ['Psychic', 'Psychic'],
				convertedEnergyCost: 2,
				damage: '',
				text:
					"Discard 1 Energy card attached to Mewtwo in order to use this attack. During your opponent's next turn, prevent all effects of attacks, including damage, done to Mewtwo.",
			},
		],
		weaknesses: [
			{
				type: 'Psychic',
				value: '×2',
			},
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/10_hires.png',
		nationalPokedexNumber: 150,
	},
	{
		id: 'base1-91',
		name: 'Bill',
		imageUrl: 'https://images.pokemontcg.io/base1/91.png',
		subtype: '',
		supertype: 'Trainer',
		number: '91',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Draw 2 cards.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/91_hires.png',
	},
	{
		id: 'base1-91',
		name: 'Bill',
		imageUrl: 'https://images.pokemontcg.io/base1/91.png',
		subtype: '',
		supertype: 'Trainer',
		number: '91',
		artist: 'Ken Sugimori',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Draw 2 cards.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/91_hires.png',
	},
	{
		id: 'base1-71',
		name: 'Computer Search',
		imageUrl: 'https://images.pokemontcg.io/base1/71.png',
		subtype: '',
		supertype: 'Trainer',
		number: '71',
		artist: 'Keiji Kinebuchi',
		rarity: 'Rare',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			'Discard 2 other cards from your hand in order to search your deck for any card and put it into your hand. Shuffle your deck afterward.',
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/71_hires.png',
	},
	{
		id: 'base1-80',
		name: 'Defender',
		imageUrl: 'https://images.pokemontcg.io/base1/80.png',
		subtype: '',
		supertype: 'Trainer',
		number: '80',
		artist: 'Keiji Kinebuchi',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Attach Defender to 1 of your Pokémon. At the end of your opponent's next turn, discard Defender. Damage done to that Pokémon by attacks is reduced by 20 (after applying Weakness and Resistance.)",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/80_hires.png',
	},
	{
		id: 'base1-93',
		name: 'Gust of Wind',
		imageUrl: 'https://images.pokemontcg.io/base1/93.png',
		subtype: '',
		supertype: 'Trainer',
		number: '93',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Choose 1 of your opponent's Benched Pokémon and switch it with his or her Active Pokémon.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/93_hires.png',
	},
	{
		id: 'base1-93',
		name: 'Gust of Wind',
		imageUrl: 'https://images.pokemontcg.io/base1/93.png',
		subtype: '',
		supertype: 'Trainer',
		number: '93',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			"Choose 1 of your opponent's Benched Pokémon and switch it with his or her Active Pokémon.",
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/93_hires.png',
	},
	{
		id: 'base1-94',
		name: 'Potion',
		imageUrl: 'https://images.pokemontcg.io/base1/94.png',
		subtype: '',
		supertype: 'Trainer',
		number: '94',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Remove up to 2 damage counters from 1 of your Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/94_hires.png',
	},
	{
		id: 'base1-88',
		name: 'Professor Oak',
		imageUrl: 'https://images.pokemontcg.io/base1/88.png',
		subtype: '',
		supertype: 'Trainer',
		number: '88',
		artist: 'Ken Sugimori',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Discard your hand, then draw 7 cards.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/88_hires.png',
	},

	{
		id: 'base1-90',
		name: 'Super Potion',
		imageUrl: 'https://images.pokemontcg.io/base1/90.png',
		subtype: '',
		supertype: 'Trainer',
		number: '90',
		artist: 'Keiji Kinebuchi',
		rarity: 'Uncommon',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: [
			'Discard 1 Energy card attached to 1 of your own Pokémon in order to remove up to 4 damage counters from that Pokémon.',
		],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/90_hires.png',
	},
	{
		id: 'base1-95',
		name: 'Switch',
		imageUrl: 'https://images.pokemontcg.io/base1/95.png',
		subtype: '',
		supertype: 'Trainer',
		number: '95',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Switch 1 of your Benched Pokémon with your Active Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/95_hires.png',
	},
	{
		id: 'base1-95',
		name: 'Switch',
		imageUrl: 'https://images.pokemontcg.io/base1/95.png',
		subtype: '',
		supertype: 'Trainer',
		number: '95',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		text: ['Switch 1 of your Benched Pokémon with your Active Pokémon.'],
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/95_hires.png',
	},

	{
		id: 'base1-100',
		name: 'Lightning Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/100.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '100',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/100_hires.png',
	},
	{
		id: 'base1-100',
		name: 'Lightning Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/100.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '100',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/100_hires.png',
	},
	{
		id: 'base1-100',
		name: 'Lightning Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/100.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '100',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/100_hires.png',
	},
	{
		id: 'base1-100',
		name: 'Lightning Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/100.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '100',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/100_hires.png',
	},
	{
		id: 'base1-100',
		name: 'Lightning Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/100.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '100',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/100_hires.png',
	},
	{
		id: 'base1-100',
		name: 'Lightning Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/100.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '100',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/100_hires.png',
	},
	{
		id: 'base1-100',
		name: 'Lightning Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/100.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '100',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/100_hires.png',
	},
	{
		id: 'base1-100',
		name: 'Lightning Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/100.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '100',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/100_hires.png',
	},
	{
		id: 'base1-100',
		name: 'Lightning Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/100.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '100',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/100_hires.png',
	},
	{
		id: 'base1-100',
		name: 'Lightning Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/100.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '100',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/100_hires.png',
	},
	{
		id: 'base1-100',
		name: 'Lightning Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/100.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '100',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/100_hires.png',
	},
	{
		id: 'base1-100',
		name: 'Lightning Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/100.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '100',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/100_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
	{
		id: 'base1-101',
		name: 'Psychic Energy',
		imageUrl: 'https://images.pokemontcg.io/base1/101.png',
		subtype: 'Basic',
		supertype: 'Energy',
		number: '101',
		artist: 'Keiji Kinebuchi',
		rarity: 'Common',
		series: 'Base',
		set: 'Base',
		setCode: 'base1',
		imageUrlHiRes: 'https://images.pokemontcg.io/base1/101_hires.png',
	},
];

module.exports = zap;
